export const SOCKET_GET_USER_INFO = 'USER_INFO';
export const SOCKET_USER_LOCK = 'USER_LOCK';
export const SOCKET_USER_UNLOCK = 'USER_UNLOCK';
export const SOCKET_USER_REMOVE_STUCK = 'USER_REMOVE_STUCK';
export const SOCKET_USER_KICK_USER = 'USER_KICK';
