export const SOCKET_GET_CARD2MOMO_RATE_LIST = 'CARD2MOMO_RATE_LIST';
export const SOCKET_SAVE_CARD2MOMO_RATE = 'CARD2MOMO_RATE_SAVE';
export const SOCKET_GET_CARD2MOMO_RATE_DETAIL = 'CARD2MOMO_RATE_GET';
export const SOCKET_GET_TELCO = 'TELCO_LIST';
