export const SOCKET_GET_ACCOUNT_LIST = 'ACCOUNT_LIST';
export const SOCKET_ADD_ACCOUNT = 'ACCOUNT_SAVE';
export const SOCKET_ENABLE_USER = 'INSIDE_USER_SET_ENABLED';
export const SOCKET_SET_PASSWORD_USER = 'INSIDE_USER_SET_PASSWORD';
export const SOCKET_GET_GROUP_LIST = 'GROUP_LIST';
