export const SOCKET_GET_ACCOUNT_LIST = 'ACCOUNT_LIST';
export const SOCKET_ADD_ACCOUNT = 'ACCOUNT_SAVE';
export const SOCKET_GET_ACCOUNT = 'ACCOUNT_GET';
export const SOCKET_GET_GROUP_LIST = 'GROUP_LIST';
