export const SOCKET_GET_ACCOUNT_SERVICE_LIST = 'ACCOUNT_SERVICE_LIST';
export const SOCKET_GET_ACCOUNT_LIST = 'ACCOUNT_LIST';
export const SOCKET_SAVE_ACCOUNT_SERVICE = 'ACCOUNT_SERVICE_SAVE';
export const SOCKET_GET_ACCOUNT_SERVICE_DETAIL = 'ACCOUNT_SERVICE_GET';
