export const SOCKET_GET_CARD_TRANSACTION_LIST = 'CARD_TRANSACTION_LIST';
export const EVENT_SOCKET_GET_TELCO = 'TELCO_LIST';
export const SOCKET_GET_ACCOUNT_LIST = 'ACCOUNT_LIST';
export const SOCKET_SAVE_ACCOUNT_SERVICE = 'ACCOUNT_SERVICE_SAVE';
export const SOCKET_GET_ACCOUNT_SERVICE_DETAIL = 'ACCOUNT_SERVICE_GET';
